module.exports = {
  MODULES: {
    STUDENTS: 'students',
    TEACHERS: 'teachers',
    CLASSES: 'classes',
    ACADEMIC_YEARS: 'academic_years',
    ROLES: 'roles',
    USERS: 'users',
    FEES: 'fees',
    TRANSPORT: 'transport',
    ATTENDANCE: 'attendance',
    PAYROLL: 'payroll',
    REPORTS: 'reports',
    GOVERNANCE: 'governance'
  },

  ACTIONS: {
    ADMISSION: 'admission',
    PROFILE_UPDATE: 'profile_update',
    REGISTRATION: 'registration',
    UPDATE: 'update',
    CREATE: 'create',
    ACTIVATE: 'activate',
    CLOSE: 'close',
    STATUS_CHANGE: 'status_change',
    DEACTIVATE: 'deactivate',
    PERMISSION_CHANGE: 'permission_change',
    ROLE_ASSIGNMENT: 'role_assignment',
    CLASS_TEACHER_ASSIGNMENT: 'class_teacher_assignment',
    INTEGRITY_VIOLATION: 'integrity_violation',
    DOCUMENT_UPLOAD: 'document_upload',
    DOCUMENT_REPLACE: 'document_replace',
    DOCUMENT_DELETE: 'document_delete',
    DOCUMENT_ACCESS: 'document_access',
    LOGIN_SUCCESS: 'login_success',
    LOGIN_FAILED: 'login_failed',
    LOGIN_BLOCKED: 'login_blocked_locked',
    LOGOUT: 'logout',
    PASSWORD_CHANGED: 'password_changed',
    ACCOUNT_UNLOCKED: 'account_unlocked',
    ACCOUNT_LOCKED: 'account_locked',
    LOCK: 'lock',
    UNLOCK: 'unlock',
    RECORD_LOCK: 'record_lock',
    RECORD_UNLOCK: 'record_unlock',
    CONFIG_CHANGE: 'config_change',
    DATA_QUALITY_WARNING: 'data_quality_warning'
  }
};
